---
- name: Monitoring | Installing etcd monitoring
  shell: "{{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/prometheus/{{ item }}"
  loop:
    - "etcd"
  register: import
  failed_when: "import.stderr and 'Warning' not in import.stderr and 'spec.clusterIP' not in import.stderr"
  until: import is succeeded
  retries: 5
  delay: 3
  when:
    - etcd.monitoring is defined
    - etcd.monitoring == true