apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: notification-manager-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: {{ .Values.operator.containers.proxy.image.repo }}:{{ .Values.operator.containers.proxy.image.tag }}
        imagePullPolicy: {{ .Values.operator.containers.proxy.image.pullPolicy }}
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources: 
        {{- toYaml .Values.operator.containers.proxy.resources | nindent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        command:
        - /notification-manager-operator
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: {{ .Values.operator.containers.operator.image.repo }}:{{ .Values.operator.containers.operator.image.tag }}
        imagePullPolicy: {{ .Values.operator.containers.operator.image.pullPolicy }}
        name: notification-manager-operator
        resources: 
        {{- toYaml .Values.operator.containers.operator.resources | nindent 10 }}
        volumeMounts:
          - mountPath: /etc/localtime
            name: host-time
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ""
          name: host-time
      serviceAccount: notification-manager-sa
      serviceAccountName: notification-manager-sa
      nodeSelector: 
      {{- toYaml .Values.operator.nodeSelector | nindent 8 }}
      affinity: 
      {{- toYaml .Values.operator.affinity | nindent 8 }}
      tolerations: 
      {{- toYaml .Values.operator.tolerations | nindent 8 }}
      
